name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              git clone https://github.com/awslabs/git-secrets
              cd git-secrets
              sudo git secrets --install
              # Add support for AWS secret scan
              sudo git secrets --register-aws
              # Scan the latest git push
              sudo git secrets --scan
              if [ $? -eq 0 ]; then
              echo "git secrets --scan OK"
              else
              echo "git secrets --scan FAIL"
